const Constants = {
    BALL_RADIUS: 20,
    BALL_X_VELOCITY: 4,
    PLATFORM_THICKNESS: 15,
    PLATFORM_TINT: 0x777684,
    PLATFORM_POOL_SIZE: 10,
    PLATFORM_MIDDLE_PERCENTAGE: 0.60,
}

export default Constants